"""
Coding Agent — generates production-ready PySpark code and a README.
Uses Claude + Jinja2 templates to produce modular, standards-compliant pipelines.
"""
from typing import Any

from tenacity import retry, stop_after_attempt, wait_exponential

from etl_agent.core.config import get_settings
from etl_agent.core.exceptions import CodeGenerationError
from etl_agent.core.logging import get_logger
from etl_agent.core.models import RunStatus
from etl_agent.core.state import GraphState
from etl_agent.prompts.code_generator import build_code_generator_prompt

logger = get_logger(__name__)


class CodingAgent:
    """Agent 2: Generates PySpark code + README from an ETLSpec."""

    def __init__(self) -> None:
        self.settings = get_settings()

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=2, max=30), reraise=True)
    async def _call_llm(self, prompt: str) -> str:
        import anthropic
        client = anthropic.AsyncAnthropic(api_key=self.settings.anthropic_api_key)
        response = await client.messages.create(
            model=self.settings.llm_model,
            max_tokens=self.settings.llm_max_tokens,
            temperature=self.settings.llm_temperature,
            messages=[{"role": "user", "content": prompt}],
        )
        return response.content[0].text

    async def run(self, state: GraphState) -> dict[str, Any]:
        etl_spec = state["etl_spec"]
        retry_count = state["retry_count"]
        previous_failure = state.get("test_results")

        logger.info("coding_agent_started", pipeline=etl_spec.pipeline_name, attempt=retry_count + 1)

        try:
            prompt = build_code_generator_prompt(
                etl_spec=etl_spec,
                previous_failure=previous_failure,
                retry_count=retry_count,
            )
            raw_response = await self._call_llm(prompt)

            # Extract code blocks from response
            import re
            code_match = re.search(r"```python\n(.*?)\n```", raw_response, re.DOTALL)
            readme_match = re.search(r"```markdown\n(.*?)\n```", raw_response, re.DOTALL)

            generated_code = code_match.group(1) if code_match else raw_response
            generated_readme = readme_match.group(1) if readme_match else _default_readme(etl_spec)

            # Validate syntax
            from etl_agent.tools.code_validator import validate_python_syntax
            validate_python_syntax(generated_code)

            logger.info("coding_agent_completed", pipeline=etl_spec.pipeline_name,
                        code_lines=len(generated_code.splitlines()))

            return {
                "generated_code": generated_code,
                "generated_readme": generated_readme,
                "retry_count": retry_count + (1 if retry_count > 0 else 0),
                "status": RunStatus.TESTING,
            }

        except Exception as e:
            logger.error("coding_agent_failed", error=str(e))
            raise CodeGenerationError(f"Code generation failed: {e}") from e


def _default_readme(etl_spec: Any) -> str:
    return f"""# {etl_spec.pipeline_name}

## Description
{etl_spec.description}

## Operations
{', '.join(op.value for op in etl_spec.operations)}

## Source
`{etl_spec.source.path}`

## Target
`{etl_spec.target.path}`

*Auto-generated by Autonomous ETL Agent*
"""
