"""
PR Agent — creates a GitHub Issue, commits generated code, and opens a PR.
Uses Claude to write intelligent commit messages.
"""
from typing import Any

from tenacity import retry, stop_after_attempt, wait_exponential

from etl_agent.core.config import get_settings
from etl_agent.core.exceptions import PRCreationError
from etl_agent.core.logging import get_logger
from etl_agent.core.models import RunStatus
from etl_agent.core.state import GraphState

logger = get_logger(__name__)


class PRAgent:
    """Agent 4: Creates GitHub Issue + branch + commit + PR."""

    def __init__(self) -> None:
        self.settings = get_settings()

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=4, max=60), reraise=True)
    async def _generate_commit_message(self, state: GraphState) -> str:
        """Use Claude to generate an intelligent commit message."""
        import anthropic
        client = anthropic.AsyncAnthropic(api_key=self.settings.anthropic_api_key)
        etl_spec = state["etl_spec"]
        prompt = (
            f"Write a concise, professional git commit message for a PySpark ETL pipeline.\n\n"
            f"Pipeline: {etl_spec.pipeline_name}\n"
            f"Description: {etl_spec.description}\n"
            f"Operations: {[op.value for op in etl_spec.operations]}\n\n"
            f"Format: <type>(<scope>): <subject>\n\n"
            f"Where type is feat/fix/refactor/test. Keep it under 72 characters."
        )
        response = await client.messages.create(
            model=self.settings.llm_model,
            max_tokens=100,
            temperature=0.0,
            messages=[{"role": "user", "content": prompt}],
        )
        return response.content[0].text.strip()

    async def run(self, state: GraphState) -> dict[str, Any]:
        from etl_agent.tools.github_tools import GitHubTools
        from github import GithubException  # type: ignore[import]

        etl_spec = state["etl_spec"]
        story = state["user_story"]
        logger.info("pr_agent_started", pipeline=etl_spec.pipeline_name)

        try:
            gh = GitHubTools(
                token=self.settings.github_token,
                target_repo=self.settings.github_target_repo,
            )

            # Step 1: Create GitHub Issue
            issue = gh.create_issue(
                title=f"[ETL] {story.title}",
                body=(
                    f"## User Story\n{story.description}\n\n"
                    f"## Acceptance Criteria\n"
                    + "\n".join(f"- {c}" for c in story.acceptance_criteria)
                    + f"\n\n## Story ID\n`{story.id}`\n\n"
                    f"*Auto-created by Autonomous ETL Agent*"
                ),
                labels=story.tags,
            )
            logger.info("github_issue_created", url=issue.html_url)

            # Step 2: Create branch
            branch_name = f"etl-agent/{story.id}-{etl_spec.pipeline_name}"
            gh.create_branch(branch_name)

            # Step 3: Generate commit message via Claude
            commit_message = await self._generate_commit_message(state)

            # Step 4: Commit generated files
            files = {
                f"src/generated_pipelines/{etl_spec.pipeline_name}.py": state["generated_code"],
                f"tests/generated_tests/test_{etl_spec.pipeline_name}.py": state["generated_tests"],
                f"src/generated_pipelines/{etl_spec.pipeline_name}_README.md": state["generated_readme"],
            }
            gh.commit_files(branch_name, files, commit_message)

            # Step 5: Open PR
            test_summary = ""
            if state.get("test_results"):
                tr = state["test_results"]
                test_summary = (
                    f"\n\n## Test Results\n"
                    f"✅ {tr.passed_tests}/{tr.total_tests} tests passed | "
                    f"Coverage: {tr.coverage_pct:.0f}%"
                )

            pr = gh.create_pull_request(
                title=f"[ETL Agent] {story.title}",
                body=(
                    f"## Summary\nAuto-generated PySpark pipeline for: **{story.title}**\n\n"
                    f"Closes #{issue.number}\n\n"
                    f"## Pipeline\n`{etl_spec.pipeline_name}`\n\n"
                    f"## Operations\n{', '.join(op.value for op in etl_spec.operations)}"
                    + test_summary
                    + f"\n\n*Auto-generated by Autonomous ETL Agent | Story: `{story.id}`*"
                ),
                head_branch=branch_name,
            )
            logger.info("pr_created", url=pr.html_url)

            return {
                "github_issue_url": issue.html_url,
                "github_branch_name": branch_name,
                "github_pr_url": pr.html_url,
                "status": RunStatus.DEPLOYING,
            }

        except GithubException as e:
            logger.error("pr_agent_failed", error=str(e))
            raise PRCreationError(f"PR creation failed: {e}") from e
