"""Unit tests for the PRAgent and GitHubTools."""
from __future__ import annotations

from unittest.mock import AsyncMock, MagicMock, patch
from uuid import uuid4

import pytest

from etl_agent.core.models import (
    DataSource,
    DataTarget,
    ETLSpec,
    OutputFormat,
    RunStatus,
    TestResult,
)
from etl_agent.core.state import GraphState


# ─── Fixtures ─────────────────────────────────────────────────────────────────

@pytest.fixture
def sample_etl_spec() -> ETLSpec:
    return ETLSpec(
        pipeline_name="rfm_analysis",
        source=DataSource(path="s3://raw/", format="parquet"),
        target=DataTarget(path="s3://processed/rfm/", format=OutputFormat.delta, mode="overwrite"),
        transformations=[],
    )


@pytest.fixture
def sample_test_results() -> TestResult:
    return TestResult(
        passed=True,
        num_passed=8,
        num_failed=0,
        coverage_pct=85.0,
    )


@pytest.fixture
def mock_github():
    """Mock the GitHub client (mock_github fixture from conftest.py)."""
    mock_repo = MagicMock()
    mock_repo.full_name = "test-org/etl-pipelines-demo"
    mock_repo.default_branch = "main"

    # Issue mock
    mock_issue = MagicMock()
    mock_issue.number = 42
    mock_issue.html_url = "https://github.com/test-org/etl-pipelines-demo/issues/42"
    mock_repo.create_issue.return_value = mock_issue

    # Branch mock
    mock_branch_ref = MagicMock()
    mock_branch_ref.ref = "refs/heads/feature/rfm-analysis-abc123"

    # File mock (for commit)
    mock_repo.get_contents.side_effect = Exception("File not found")

    # PR mock
    mock_pr = MagicMock()
    mock_pr.html_url = "https://github.com/test-org/etl-pipelines-demo/pull/43"
    mock_pr.number = 43
    mock_repo.create_pull.return_value = mock_pr

    mock_gh = MagicMock()
    mock_gh.get_repo.return_value = mock_repo

    return mock_gh


# ─── Tests: GitHubTools ───────────────────────────────────────────────────────

class TestGitHubTools:
    def test_create_issue_returns_url(self, mock_github) -> None:
        from etl_agent.tools.github_tools import GitHubTools

        with patch("etl_agent.tools.github_tools.Github", return_value=mock_github):
            tools = GitHubTools(token="test-token", repo="test-org/etl-pipelines-demo")
            issue_url = tools.create_issue(
                title="feat: rfm_analysis ETL pipeline",
                body="Auto-generated by Autonomous ETL Agent",
                labels=["etl-agent", "enhancement"],
            )

        assert "github.com" in issue_url
        assert "/issues/" in issue_url

    def test_create_branch_from_main(self, mock_github) -> None:
        from etl_agent.tools.github_tools import GitHubTools

        with patch("etl_agent.tools.github_tools.Github", return_value=mock_github):
            tools = GitHubTools(token="test-token", repo="test-org/etl-pipelines-demo")
            branch_name = tools.create_branch(base_branch="main", prefix="feature/rfm-analysis")

        assert branch_name is not None
        assert "rfm" in branch_name.lower() or "feature" in branch_name.lower()

    def test_create_pull_request_returns_url(self, mock_github) -> None:
        from etl_agent.tools.github_tools import GitHubTools

        with patch("etl_agent.tools.github_tools.Github", return_value=mock_github):
            tools = GitHubTools(token="test-token", repo="test-org/etl-pipelines-demo")
            pr_url = tools.create_pull_request(
                title="feat: rfm_analysis auto-generated ETL pipeline",
                body="Closes #42\n\nGenerated by ETL Agent",
                head_branch="feature/rfm-analysis-abc123",
                base_branch="main",
            )

        assert "github.com" in pr_url
        assert "/pull/" in pr_url

    def test_commit_files_creates_new_file(self, mock_github) -> None:
        from etl_agent.tools.github_tools import GitHubTools

        with patch("etl_agent.tools.github_tools.Github", return_value=mock_github):
            tools = GitHubTools(token="test-token", repo="test-org/etl-pipelines-demo")
            tools.commit_files(
                branch="feature/rfm-analysis-abc123",
                files={"pipelines/rfm_analysis/pipeline.py": "# generated code"},
                message="feat(etl): add rfm_analysis pipeline [ETL Agent]",
            )

        mock_github.get_repo.return_value.create_file.assert_called_once()


# ─── Tests: PRAgent ───────────────────────────────────────────────────────────

class TestPRAgent:
    @pytest.mark.asyncio
    async def test_pr_agent_creates_issue_and_pr(
        self,
        sample_etl_spec: ETLSpec,
        sample_test_results: TestResult,
        mock_github,
    ) -> None:
        from etl_agent.agents.pr_agent import PRAgent

        agent = PRAgent()

        mock_commit_message_response = MagicMock(
            content="feat(etl): add rfm_analysis pipeline — RFM customer segmentation"
        )

        with (
            patch("etl_agent.agents.pr_agent.GitHubTools") as MockGitHub,
            patch.object(agent, "_llm") as mock_llm,
        ):
            mock_tools = MagicMock()
            mock_tools.create_issue.return_value = "https://github.com/org/repo/issues/42"
            mock_tools.create_branch.return_value = "feature/rfm-analysis-abc123"
            mock_tools.create_pull_request.return_value = "https://github.com/org/repo/pull/43"
            MockGitHub.return_value = mock_tools
            mock_llm.ainvoke = AsyncMock(return_value=mock_commit_message_response)

            state: GraphState = {
                "etl_spec": sample_etl_spec,
                "generated_code": "def run_pipeline(): pass",
                "generated_tests": "def test_schema(): assert True",
                "generated_readme": "# rfm_analysis",
                "test_results": sample_test_results,
                "run_id": uuid4(),
                "status": RunStatus.PR_CREATING,
                "retry_count": 0,
                "max_retries": 2,
                "messages": [],
                "awaiting_approval": False,
            }

            result = await agent(state)

        assert result.get("github_pr_url") is not None
        assert result.get("github_issue_url") is not None
        assert result["status"] == RunStatus.DEPLOYING

    @pytest.mark.asyncio
    async def test_pr_agent_failure_sets_error_status(
        self,
        sample_etl_spec: ETLSpec,
        sample_test_results: TestResult,
    ) -> None:
        from etl_agent.agents.pr_agent import PRAgent

        agent = PRAgent()

        with patch("etl_agent.agents.pr_agent.GitHubTools") as MockGitHub:
            mock_tools = MagicMock()
            mock_tools.create_issue.side_effect = Exception("GitHub API error")
            MockGitHub.return_value = mock_tools

            result = await agent(
                {
                    "etl_spec": sample_etl_spec,
                    "generated_code": "def run_pipeline(): pass",
                    "test_results": sample_test_results,
                    "run_id": uuid4(),
                    "status": RunStatus.PR_CREATING,
                    "retry_count": 0,
                    "max_retries": 2,
                    "messages": [],
                    "awaiting_approval": False,
                }
            )

        assert result["status"] == RunStatus.FAILED

    def test_route_after_pr_with_url(self, sample_etl_spec: ETLSpec) -> None:
        from etl_agent.core.state import route_after_pr

        state: GraphState = {
            "etl_spec": sample_etl_spec,
            "run_id": uuid4(),
            "github_pr_url": "https://github.com/org/repo/pull/43",
            "status": RunStatus.DEPLOYING,
            "retry_count": 0,
            "max_retries": 2,
            "messages": [],
            "awaiting_approval": False,
        }
        assert route_after_pr(state) == "deploy_agent"

    def test_route_after_pr_without_url_routes_to_failure(self, sample_etl_spec: ETLSpec) -> None:
        from etl_agent.core.state import route_after_pr

        state: GraphState = {
            "etl_spec": sample_etl_spec,
            "run_id": uuid4(),
            "status": RunStatus.FAILED,
            "retry_count": 0,
            "max_retries": 2,
            "messages": [],
            "awaiting_approval": False,
        }
        assert route_after_pr(state) == "failure"
